# https://docs.docker.com/compose/compose-file/compose-file-v2/

version: '2.3'
services:
  frontend:
    build:
      # Start this container from an image built using the following directory
      # and Dockerfile
      context: ../
      dockerfile: Dockerfile
    # Pass in AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
    env_file:
      - aws.env.secret
    # Environment variables
    environment:
      FRONTEND_URL: ${FRONTEND_URL:-https://yo.com:3012}
      BACKEND_URL: ${BACKEND_URL:-https://app:4012}
      S3_BUCKET: ${S3_BUCKET:-dev-privacy-page-transcend-io}
    ports:
      # Exposes 3012 from the container to the host on 3012
      - "3012:3012"
    volumes:
      # Mount the server for dev only (not needed)
      - "../server:/app/server"
      # Mount the certs
      - "../server/ssl:/ssl"
